import monsteraImg from './assets/images/monstera_deliciosa_specimen_1791048137675.jpg';
import morphoImg from './assets/images/morpho_menelaus_specimen_1791048148029.jpg';
import amanitaImg from './assets/images/amanita_muscaria_specimen_1791048159371.jpg';
import frogImg from './assets/images/dendrobates_tinctorius_specimen_1791048169462.jpg';
import passifloraImg from './assets/images/passiflora_caerulea_specimen_1791048179254.jpg';
import { CollectorProfile, Specimen, SpecimenComment, SpecimenLike } from './types';

export const SEED_PROFILES: CollectorProfile[] = [
  {
    uid: 'curator_valeria_botanica',
    handle: 'valeria.herbario',
    displayName: 'Dra. Valeria Montes',
    bio: 'Botánica tropical y exploradora de bosque nuboso. Documentando flora epífita, cactáceas, pasifloras y aráceas neotropicales.',
    avatarUrl: passifloraImg,
    location: 'Sierra Madre · Veracruz',
    specialty: 'Flora Neotropical · Cactaceae & Araceae',
    isPublic: true,
  },
  {
    uid: 'curator_mateo_fauna',
    handle: 'mateo.naturalista',
    displayName: 'Mateo Ríos',
    bio: 'Fotógrafo de entomología, herpetofauna y micología de selva húmeda. Registro taxonómico de campo.',
    avatarUrl: morphoImg,
    location: 'Península de Osa · Costa Rica',
    specialty: 'Lepidoptera · Dendrobatidae',
    isPublic: true,
  },
];

export const SEED_SPECIMENS: Specimen[] = [
  {
    id: 'seed_monstera_01',
    ownerId: 'curator_valeria_botanica',
    ownerHandle: 'valeria.herbario',
    ownerName: 'Dra. Valeria Montes',
    scientificName: 'Monstera deliciosa',
    commonName: 'Costilla de Adán',
    category: 'plant',
    family: 'Araceae',
    kingdom: 'Plantae',
    photoDataUrl: monsteraImg,
    locationName: 'Reserva Biológica Los Tuxtlas',
    coordinates: '18.5844° N, 95.0750° W · 640 msnm',
    habitat: 'Sotobosque húmedo tropical perennifolio',
    conservationStatus: 'Preocupación menor (LC)',
    notes: 'Ejemplar adulto trepador sobre corteza de Ficus. Fenestraciones laminares profundas bien desarrolladas para captación de luz filtrada y resistencia a lluvias torrenciales.',
    confidence: 99,
    observedDate: '2026-09-18',
    isPublic: true,
  },
  {
    id: 'seed_passiflora_02',
    ownerId: 'curator_valeria_botanica',
    ownerHandle: 'valeria.herbario',
    ownerName: 'Dra. Valeria Montes',
    scientificName: 'Passiflora caerulea',
    commonName: 'Pasionaria Azul',
    category: 'plant',
    family: 'Passifloraceae',
    kingdom: 'Plantae',
    photoDataUrl: passifloraImg,
    locationName: 'Cañón del Río Blanco',
    coordinates: '18.8312° N, 97.1489° W · 1,280 msnm',
    habitat: 'Borde de bosque mesófilo de montaña',
    conservationStatus: 'Preocupación menor (LC)',
    notes: 'Floración matutina en enredadera leñosa con zarcillos axilares. Corona de filamentos radiados bicolores azul-púrpura y blanco impecable.',
    confidence: 98,
    observedDate: '2026-09-24',
    isPublic: true,
  },
  {
    id: 'seed_morpho_03',
    ownerId: 'curator_mateo_fauna',
    ownerHandle: 'mateo.naturalista',
    ownerName: 'Mateo Ríos',
    scientificName: 'Morpho menelaus',
    commonName: 'Mariposa Morfo Azul',
    category: 'animal',
    family: 'Nymphalidae',
    kingdom: 'Animalia',
    photoDataUrl: morphoImg,
    locationName: 'Parque Nacional Corcovado',
    coordinates: '8.5408° N, 83.5708° W · 120 msnm',
    habitat: 'Dosel bajo y claros de bosque lluvioso tropical',
    conservationStatus: 'Preocupación menor (LC)',
    notes: 'Coloración azul iridiscente producida por microestructuras de difracción en las escamas alares. Observada posada sobre rama cubierta de briofitas.',
    confidence: 97,
    observedDate: '2026-09-27',
    isPublic: true,
  },
  {
    id: 'seed_dendrobates_04',
    ownerId: 'curator_mateo_fauna',
    ownerHandle: 'mateo.naturalista',
    ownerName: 'Mateo Ríos',
    scientificName: 'Dendrobates tinctorius',
    commonName: 'Rana Dardo Venenoso Tintorera',
    category: 'animal',
    family: 'Dendrobatidae',
    kingdom: 'Animalia',
    photoDataUrl: frogImg,
    locationName: 'Estación Biológica La Selva',
    coordinates: '10.4308° N, 84.0070° W · 85 msnm',
    habitat: 'Hojarasca húmeda y bromelias epífitas',
    conservationStatus: 'Preocupación menor (LC)',
    notes: 'Coloración aposemática amarillo-cobalto de alto contraste. Individuo activo tras lluvia matinal sobre axila foliar de bromelia.',
    confidence: 96,
    observedDate: '2026-09-30',
    isPublic: true,
  },
  {
    id: 'seed_amanita_05',
    ownerId: 'curator_valeria_botanica',
    ownerHandle: 'valeria.herbario',
    ownerName: 'Dra. Valeria Montes',
    scientificName: 'Amanita muscaria',
    commonName: 'Matamoscas · Hongo Escarlata',
    category: 'fungi',
    family: 'Amanitaceae',
    kingdom: 'Fungi',
    photoDataUrl: amanitaImg,
    locationName: 'Bosque de Coníferas Cofre de Perote',
    coordinates: '19.4931° N, 97.1475° W · 3,150 msnm',
    habitat: 'Suelo ácido en simbiosis micorrízica con Pinus',
    conservationStatus: 'No evaluado (NE)',
    notes: 'Basidioma joven con píleo rojo escarlata brillante cubierto de restos blancos del velo universal. Anillo membranoso intacto.',
    confidence: 99,
    observedDate: '2026-10-01',
    isPublic: true,
  },
];

export const SEED_LIKES: SpecimenLike[] = [
  {
    id: 'seed_like_1',
    specimenId: 'seed_monstera_01',
    userId: 'curator_mateo_fauna',
    userHandle: 'mateo.naturalista',
    isPublic: true,
  },
  {
    id: 'seed_like_2',
    specimenId: 'seed_passiflora_02',
    userId: 'curator_mateo_fauna',
    userHandle: 'mateo.naturalista',
    isPublic: true,
  },
  {
    id: 'seed_like_3',
    specimenId: 'seed_morpho_03',
    userId: 'curator_valeria_botanica',
    userHandle: 'valeria.herbario',
    isPublic: true,
  },
  {
    id: 'seed_like_4',
    specimenId: 'seed_dendrobates_04',
    userId: 'curator_valeria_botanica',
    userHandle: 'valeria.herbario',
    isPublic: true,
  },
  {
    id: 'seed_like_5',
    specimenId: 'local_initial_monstera',
    userId: 'curator_valeria_botanica',
    userHandle: 'valeria.herbario',
    isPublic: true,
  },
];

export const SEED_COMMENTS: SpecimenComment[] = [
  {
    id: 'seed_comment_1',
    specimenId: 'seed_monstera_01',
    authorId: 'curator_mateo_fauna',
    authorHandle: 'mateo.naturalista',
    authorName: 'Mateo Ríos',
    text: 'Excelente registro foliar de Araceae. Las fenestraciones secundarias se ven muy nítidas.',
    isPublic: true,
  },
  {
    id: 'seed_comment_2',
    specimenId: 'seed_morpho_03',
    authorId: 'curator_valeria_botanica',
    authorHandle: 'valeria.herbario',
    authorName: 'Dra. Valeria Montes',
    text: '¡Qué nitidez en las escamas iridiscentes! Gran hallazgo en Corcovado.',
    isPublic: true,
  },
  {
    id: 'seed_comment_3',
    specimenId: 'seed_passiflora_02',
    authorId: 'curator_mateo_fauna',
    authorHandle: 'mateo.naturalista',
    authorName: 'Mateo Ríos',
    text: 'La estructura de la corona radiada en Passiflora caerulea siempre impresiona.',
    isPublic: true,
  },
  {
    id: 'seed_comment_4',
    specimenId: 'local_initial_monstera',
    authorId: 'curator_valeria_botanica',
    authorHandle: 'valeria.herbario',
    authorName: 'Dra. Valeria Montes',
    text: '¡Gran ejemplar para iniciar tu herbario en Biofolio!',
    isPublic: true,
  },
];

// Offline & Static Host taxonomic knowledge base
export const OFFLINE_TAXONOMY_DICTIONARY: Array<{
  keywords: string[];
  scientificName: string;
  commonName: string;
  category: 'plant' | 'animal' | 'fungi';
  family: string;
  kingdom: string;
  conservationStatus: string;
  habitat: string;
  description: string;
  similarSpecies: string[];
}> = [
  {
    keywords: ['lophophora', 'peyote', 'hikuri', 'cactus', 'biznaga', 'desierto', 'cactaceae'],
    scientificName: 'Lophophora williamsii',
    commonName: 'Peyote · Hikuri',
    category: 'plant',
    family: 'Cactaceae',
    kingdom: 'Plantae',
    conservationStatus: 'Vulnerable (VU)',
    habitat: 'Matorral xerófilo y suelos calcáreos del Desierto Chihuahuense',
    description: 'Cactácea globosa sin espinas de color verde azulado glauco, con costillas redondeadas, areolas lanosas blancas y flor apical rosada.',
    similarSpecies: [
      'Lophophora diffusa (Peyote de Querétaro)',
      'Astrophytum asterias (Falso Peyote)',
    ],
  },
  {
    keywords: ['monstera', 'costilla', 'adan', 'hoja', 'tropical'],
    scientificName: 'Monstera deliciosa',
    commonName: 'Costilla de Adán',
    category: 'plant',
    family: 'Araceae',
    kingdom: 'Plantae',
    conservationStatus: 'Preocupación menor (LC)',
    habitat: 'Sotobosque húmedo tropical',
    description: 'Planta trepadora hemiepífita caracterizada por grandes hojas coriáceas fenestradas y raíces aéreas.',
    similarSpecies: [
      'Monstera adansonii (Monstera agujereada)',
      'Philodendron bipinnatifidum (Filodendro)',
    ],
  },
  {
    keywords: ['mariposa', 'morpho', 'azul', 'butterfly', 'insecto'],
    scientificName: 'Morpho menelaus',
    commonName: 'Mariposa Morfo Azul',
    category: 'animal',
    family: 'Nymphalidae',
    kingdom: 'Animalia',
    conservationStatus: 'Preocupación menor (LC)',
    habitat: 'Bosques tropicales neotropicales',
    description: 'Lepidóptero diurno de gran envergadura con alas dorsales azul metálico por iridiscencia estructural.',
    similarSpecies: [
      'Morpho peleides (Morfo común)',
      'Morpho helenor (Morfo azul bandeada)',
    ],
  },
  {
    keywords: ['rana', 'frog', 'dendrobates', 'anfibio', 'dardo'],
    scientificName: 'Dendrobates tinctorius',
    commonName: 'Rana Dardo Venenoso Tintorera',
    category: 'animal',
    family: 'Dendrobatidae',
    kingdom: 'Animalia',
    conservationStatus: 'Preocupación menor (LC)',
    habitat: 'Selva húmeda tropical baja',
    description: 'Anfibio anuro diurno con patrón aposemático azul y amarillo; habita entre bromelias y hojarasca.',
    similarSpecies: [
      'Dendrobates auratus (Rana dardo verdinegra)',
      'Dendrobates leucomelas (Rana dardo de bandas amarillas)',
    ],
  },
  {
    keywords: ['hongo', 'seta', 'amanita', 'fungi', 'rojo'],
    scientificName: 'Amanita muscaria',
    commonName: 'Matamoscas',
    category: 'fungi',
    family: 'Amanitaceae',
    kingdom: 'Fungi',
    conservationStatus: 'Preocupación menor (LC)',
    habitat: 'Bosques templados de pinos y abedules',
    description: 'Hongo basidiomiceto ectomicorrízico con sombrero rojo intenso salpicado de verrugas blancas.',
    similarSpecies: [
      'Amanita caesarea (Oronja)',
      'Amanita flavoconia (Amanita de parches amarillos)',
    ],
  },
  {
    keywords: ['pasionaria', 'passiflora', 'flor', 'enredadera'],
    scientificName: 'Passiflora caerulea',
    commonName: 'Pasionaria Azul',
    category: 'plant',
    family: 'Passifloraceae',
    kingdom: 'Plantae',
    conservationStatus: 'Preocupación menor (LC)',
    habitat: 'Bordes de bosque y matorrales húmedos',
    description: 'Trepadora perenne con zarcillos y flores complejas de filamentos radiados azul-violáceos.',
    similarSpecies: [
      'Passiflora incarnata (Pasiflora morada)',
      'Passiflora edulis (Maracuyá)',
    ],
  },
];
